# Generated by Django 3.0.2 on 2020-02-26 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=30, verbose_name='使用者名稱')),
                ('upwd', models.CharField(max_length=20, verbose_name='密碼')),
                ('ubd', models.DateField(verbose_name='生日')),
                ('uemail', models.EmailField(max_length=254, verbose_name='信箱')),
                ('ugender', models.CharField(choices=[('M', '男'), ('W', '女')], max_length=2, null=True, verbose_name='性別')),
                ('uphoto', models.ImageField(blank=True, null=True, upload_to='static/upload', verbose_name='大頭照')),
                ('uintro', models.TextField(blank=True, max_length=300, verbose_name='自我介紹')),
                ('ucredit', models.CharField(blank=True, max_length=16, null=True, verbose_name='信用卡號')),
                ('ufriend', models.CharField(blank=True, max_length=30, null=True, verbose_name='朋友群')),
                ('usubs', models.CharField(blank=True, max_length=30, null=True, verbose_name='訂閱對象')),
                ('isActive', models.BooleanField(blank=True, default=True, verbose_name='激活用戶')),
            ],
            options={
                'verbose_name': '會員',
                'verbose_name_plural': '會員',
                'db_table': 'user',
                'ordering': ['uname'],
            },
        ),
        migrations.CreateModel(
            name='FilmLibrary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50, verbose_name='影片名稱')),
                ('ftype', models.CharField(max_length=10, verbose_name='影片類型')),
                ('fintro', models.TextField(blank=True, max_length=300, verbose_name='影片簡介')),
                ('fquality', models.CharField(max_length=10, verbose_name='影片畫質')),
                ('fauthor', models.CharField(max_length=30, verbose_name='影片作者')),
                ('fdate', models.DateTimeField(verbose_name='上傳日期')),
                ('ftime', models.TimeField(verbose_name='影片時間')),
                ('flike', models.IntegerField(verbose_name='按讚數')),
                ('fcommet', models.TextField(max_length=300, verbose_name='影片留言')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.User', verbose_name='作者帳號')),
            ],
            options={
                'verbose_name': '影片庫',
                'verbose_name_plural': '影片庫',
                'db_table': 'FilmLibrary',
                'ordering': ['fdate'],
            },
        ),
        migrations.CreateModel(
            name='Creditcard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_num', models.CharField(blank=True, max_length=16, null=True, verbose_name='卡號')),
                ('c_date', models.CharField(blank=True, max_length=2, null=True, verbose_name='有效日期')),
                ('c_year', models.CharField(blank=True, max_length=2, null=True, verbose_name='有效年限')),
                ('c_authcode', models.CharField(blank=True, max_length=3, null=True, verbose_name='授權碼')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.User', verbose_name='授權會員')),
            ],
            options={
                'verbose_name': '信用卡',
                'verbose_name_plural': '信用卡',
                'db_table': 'Creditcard',
            },
        ),
    ]
