# Generated by Django 3.0.2 on 2020-02-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Creditcard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_num', models.CharField(max_length=16)),
                ('c_date', models.CharField(max_length=2)),
                ('c_year', models.CharField(max_length=2)),
                ('c_authcode', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'creditcard',
            },
        ),
        migrations.CreateModel(
            name='FilmLibrary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('ftype', models.CharField(max_length=10)),
                ('fintro', models.TextField(max_length=300)),
                ('fquality', models.CharField(max_length=10)),
                ('fauthor', models.CharField(max_length=30)),
                ('fdate', models.DateTimeField()),
                ('ftime', models.DateTimeField()),
                ('flike', models.IntegerField()),
                ('fcommet', models.TextField(max_length=300)),
            ],
            options={
                'db_table': 'fname',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=30)),
                ('upwd', models.CharField(max_length=20)),
                ('ubd', models.DateField()),
                ('uemail', models.EmailField(max_length=254)),
                ('uphoto', models.ImageField(upload_to='')),
                ('uintro', models.TextField(max_length=300)),
                ('ucredit', models.CharField(max_length=16)),
                ('ufriend', models.CharField(max_length=30)),
                ('usubs', models.CharField(max_length=30)),
                ('isActive', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
