# Generated by Django 3.0.2 on 2020-03-03 08:14

import creditcards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ucreditcard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc_number', creditcards.models.CardNumberField(max_length=25, verbose_name='卡號')),
                ('cc_expiry', creditcards.models.CardExpiryField(verbose_name='有效日期')),
                ('cc_code', creditcards.models.SecurityCodeField(max_length=4, verbose_name='授權碼')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='ugender',
            field=models.CharField(max_length=2, null=True, verbose_name='性別'),
        ),
    ]
