# Generated by Django 3.0.2 on 2020-03-16 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ucreditcard',
            old_name='user_id',
            new_name='user',
        ),
    ]
