# Generated by Django 3.0.2 on 2020-02-11 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditcard',
            options={'verbose_name': '信用卡', 'verbose_name_plural': '信用卡'},
        ),
        migrations.AlterModelOptions(
            name='filmlibrary',
            options={'verbose_name': '影片庫', 'verbose_name_plural': '影片庫'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '會員', 'verbose_name_plural': '會員'},
        ),
        migrations.AddField(
            model_name='creditcard',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.User'),
        ),
        migrations.AddField(
            model_name='filmlibrary',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uname',
            field=models.CharField(max_length=30, verbose_name='使用者名稱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uphoto',
            field=models.ImageField(null=True, upload_to='static/upload'),
        ),
        migrations.AlterModelTable(
            name='creditcard',
            table='Creditcard',
        ),
        migrations.AlterModelTable(
            name='filmlibrary',
            table='FilmLibrary',
        ),
    ]
