# Generated by Django 3.0.2 on 2020-03-03 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20200303_1614'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ucreditcard',
            options={'verbose_name': '信用卡庫', 'verbose_name_plural': '信用卡庫'},
        ),
        migrations.AlterModelTable(
            name='ucreditcard',
            table='Ucreditcard',
        ),
    ]
