# Generated by Django 3.0.2 on 2020-02-11 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20200211_1353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filmlibrary',
            options={'ordering': ['fdate'], 'verbose_name': '影片庫', 'verbose_name_plural': '影片庫'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['uname'], 'verbose_name': '會員', 'verbose_name_plural': '會員'},
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='c_authcode',
            field=models.CharField(max_length=3, verbose_name='授權碼'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='c_date',
            field=models.CharField(max_length=2, verbose_name='有效日期'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='c_num',
            field=models.CharField(max_length=16, verbose_name='卡號'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='c_year',
            field=models.CharField(max_length=2, verbose_name='有效年限'),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.User', verbose_name='授權會員'),
        ),
        migrations.AlterField(
            model_name='filmlibrary',
            name='fauthor',
            field=models.CharField(max_length=30, verbose_name='影片作者'),
        ),
        migrations.AlterField(
            model_name='filmlibrary',
            name='fcommet',
            field=models.TextField(max_length=300, verbose_name='影片留言'),
        ),
        migrations.AlterField(
            model_name='filmlibrary',
            name='fdate',
            field=models.DateTimeField(verbose_name='上傳日期'),
        ),
        migrations.AlterField(
            model_name='filmlibrary',
            name='fintro',
            field=models.TextField(max_length=300, verbose_name='影片簡介'),
        ),
        migrations.AlterField(
            model_name='filmlibrary',
            name='flike',
            field=models.IntegerField(verbose_name='按讚數'),
        ),
        migrations.AlterField(
            model_name='filmlibrary',
            name='fname',
            field=models.CharField(max_length=50, verbose_name='影片名稱'),
        ),
        migrations.AlterField(
            model_name='filmlibrary',
            name='fquality',
            field=models.CharField(max_length=10, verbose_name='影片畫質'),
        ),
        migrations.AlterField(
            model_name='filmlibrary',
            name='ftime',
            field=models.TimeField(verbose_name='影片時間'),
        ),
        migrations.AlterField(
            model_name='filmlibrary',
            name='ftype',
            field=models.CharField(max_length=10, verbose_name='影片類型'),
        ),
        migrations.AlterField(
            model_name='user',
            name='isActive',
            field=models.BooleanField(default=True, verbose_name='激活用戶'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ubd',
            field=models.DateField(verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ucredit',
            field=models.CharField(max_length=16, verbose_name='信用卡號'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uemail',
            field=models.EmailField(max_length=254, verbose_name='信箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ufriend',
            field=models.CharField(max_length=30, verbose_name='朋友群'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uintro',
            field=models.TextField(max_length=300, verbose_name='自我介紹'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uname',
            field=models.CharField(max_length=30, verbose_name='名稱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uphoto',
            field=models.ImageField(null=True, upload_to='static/upload', verbose_name='大頭照'),
        ),
        migrations.AlterField(
            model_name='user',
            name='upwd',
            field=models.CharField(max_length=20, verbose_name='密碼'),
        ),
        migrations.AlterField(
            model_name='user',
            name='usubs',
            field=models.CharField(max_length=30, verbose_name='訂閱對象'),
        ),
    ]
