# Generated by Django 3.0.2 on 2020-02-11 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20200211_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmlibrary',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.User', verbose_name='作者帳號'),
        ),
    ]
