# Generated by Django 3.0.2 on 2020-03-10 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20200303_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='ucreditcard',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='index.User', verbose_name='授權會員'),
        ),
        migrations.DeleteModel(
            name='Creditcard',
        ),
    ]
