# Generated by Django 3.0.2 on 2020-02-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20200211_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmlibrary',
            name='fintro',
            field=models.TextField(blank=True, max_length=300, verbose_name='影片簡介'),
        ),
        migrations.AlterField(
            model_name='user',
            name='isActive',
            field=models.BooleanField(blank=True, default=True, verbose_name='激活用戶'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ucredit',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='信用卡號'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ufriend',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='朋友群'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uintro',
            field=models.TextField(blank=True, max_length=300, verbose_name='自我介紹'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uphoto',
            field=models.ImageField(blank=True, null=True, upload_to='static/upload', verbose_name='大頭照'),
        ),
        migrations.AlterField(
            model_name='user',
            name='usubs',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='訂閱對象'),
        ),
    ]
