# Generated by Django 3.0.2 on 2020-02-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20200211_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ugender',
            field=models.CharField(choices=[(1, '男'), (2, '女')], max_length=2, null=True),
        ),
    ]
