# Generated by Django 3.0.2 on 2020-03-14 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20200314_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uphoto',
            field=models.ImageField(null=True, upload_to='static/upload/', verbose_name='大頭照'),
        ),
    ]
