# Generated by Django 3.0.2 on 2020-02-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_user_ugender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ugender',
            field=models.CharField(choices=[(1, '男'), (2, '女')], max_length=2, null=True, verbose_name='性別'),
        ),
    ]
