# Generated by Django 3.0.2 on 2020-02-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20200211_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ugender',
            field=models.CharField(choices=[('M', '男'), ('W', '女')], max_length=2, null=True, verbose_name='性別'),
        ),
    ]
