# Generated by Django 3.0.2 on 2020-03-20 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_auto_20200318_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uphoto',
            field=models.FileField(blank=True, null=True, upload_to='upload/', verbose_name='大頭照'),
        ),
    ]
