# Generated by Django 3.0.2 on 2020-03-26 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_auto_20200320_1601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filmlibrary',
            options={'ordering': ['-ftime'], 'verbose_name': '影片庫', 'verbose_name_plural': '影片庫'},
        ),
        migrations.AddField(
            model_name='filmlibrary',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='filmlibrary',
            name='videofile',
            field=models.FileField(null=True, upload_to='videos/%Y/%m/%d/', verbose_name='影片'),
        ),
        migrations.AlterField(
            model_name='filmlibrary',
            name='fdate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上傳日期'),
        ),
    ]
