# Generated by Django 3.0.2 on 2020-03-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_auto_20200326_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmlibrary',
            name='fcommet',
            field=models.TextField(max_length=300, null=True, verbose_name='影片留言'),
        ),
        migrations.AlterField(
            model_name='filmlibrary',
            name='flike',
            field=models.IntegerField(null=True, verbose_name='按讚數'),
        ),
    ]
