# Generated by Django 3.0.2 on 2020-03-27 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_auto_20200326_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmlibrary',
            name='slug',
        ),
    ]
