# Generated by Django 3.0.2 on 2020-04-02 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0018_auto_20200402_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmlibrary',
            name='fcommet',
            field=models.IntegerField(null=True, verbose_name='留言數'),
        ),
    ]
